<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/02_03_SVD_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example: Singular Value Decomposition

In [10]:
import numpy as np

# 2x3 matrix
A = np.array([[3, 2, 2],
              [2, 3, -2]])

# Apply SVD
U, S, V = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nS:")
print(S)
print("\nV:")
V


Matrix A:
[[ 3  2  2]
 [ 2  3 -2]]

U:
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]

S:
[5. 3.]

V:


array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])