<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/02_03_SVD_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example: Singular Value Decomposition

In [ ]:
import numpy as np

# 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Apply SVD
U, S, VT = np.linalg.svd(A)

print("Matrix A:")
print(A)
print("\nU:")
print(U)
print("\nS:")
print(S)
print("\nVT:")
VT


Matrix A:
[[1 2 3]
 [4 5 6]]

U:
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

S:
[9.508032   0.77286964]

VT:


array([[-0.42866713, -0.56630692, -0.7039467 ],
       [ 0.80596391,  0.11238241, -0.58119908],
       [ 0.40824829, -0.81649658,  0.40824829]])