<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/02_3_SVD_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Example: Singular Value Decomposition

In [4]:
import numpy as np

# 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Apply SVD
U, S, VT = np.linalg.svd(A)

print("Matrix A:", A.shape)
print(A)
print("\nU:", U.shape)
print(U)
print("\nS:"), S.shape
print(S)
print("\nVT:", VT.shape)
print(VT)


Matrix A: (2, 3)
[[1 2 3]
 [4 5 6]]

U: (2, 2)
[[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]

S:
[9.508032   0.77286964]

VT: (3, 3)
[[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]
 [ 0.40824829 -0.81649658  0.40824829]]
