<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/03_40_Background.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np

A = np.array([[2, 4, 6], [8, 10, 12]])

print("A matrix:")
print(A,"\n")

print("Flattened A matrix:")
print(A.flatten(),"\n")

print("mean of A, (flattened)      :",np.mean(A))
print("mean of A, axis = 0 (column):", np.mean(A,axis=0))
print("mean of A, axis = 1 (row)   :",np.mean(A,axis=1),"\n")

print("variance of A               :",np.var(A))
print("std deviation of A          :",np.std(A))
print("std deviation of A          :",np.sqrt(np.var(A)))

# Calculate variance and stddev of columns of A


# Calculate variance and stddev of rows of A


A matrix:
[[ 2  4  6]
 [ 8 10 12]] 

Flattened A matrix:
[ 2  4  6  8 10 12] 

mean of A, (flattened)      : 7.0
mean of A, axis = 0 (column): [5. 7. 9.]
mean of A, axis = 1 (row)   : [ 4. 10.] 

variance of A               : 11.666666666666666
std deviation of A          : 3.415650255319866
std deviation of A          : 3.415650255319866


In [30]:
# np.random.randn, return a sample (or samples) from the “standard normal” distribution.
# It draw samples from a standard Normal distribution (mean=0, stdev=1).
A = np.random.randn(2,4)
print("Random A:\n", A)
print("Mean of A                     :",np.mean(A))
print("Standard deviation of A       :",np.std(A))

print("Mean of A (rows)              :",np.mean(A,axis=1))
print("Standard deviation of A (rows):",np.std(A,axis=1))



Random A:
 [[-1.65516405  1.33033879  0.62442188  1.09852268]
 [ 0.42532827 -0.16403383  0.21271184  0.16102213]]
Mean of A                     : 0.25414346570369806
Standard deviation of A       : 0.856467933307905
Mean of A (rows)              : [0.34952983 0.15875711]
Standard deviation of A (rows): [1.18504638 0.21105119]


In [31]:
# Construct an array by repeating given number by repetitions

a = np.tile(1, 5)
print(a)

[1 1 1 1 1]


In [32]:
b = np.tile([1, 2], 5)
print(b)

[1 2 1 2 1 2 1 2 1 2]


In [33]:
c = np.tile([1, 3], (5,2))
print(c)

[[1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]
 [1 3 1 3]]


In [34]:
c = np.tile([1, 3], (5,2)).T
print(c)

[[1 1 1 1 1]
 [3 3 3 3 3]
 [1 1 1 1 1]
 [3 3 3 3 3]]


In [35]:
d = np.tile([1, 3], (2,5))
print(d)

[[1 3 1 3 1 3 1 3 1 3]
 [1 3 1 3 1 3 1 3 1 3]]
