<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/03_40_Background.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

A = np.array([[2, 4, 6], [8, 10, 12]])

print("A matrix:")
print(A,"\n")

print("Flattened A matrix:")
print(A.flatten(),"\n")

print("mean of A, (flattened):",np.mean(A))
print("mean of A, axis = 0 (column):", np.mean(A,axis=0))
print("mean of A, axis = 1 (row):",np.mean(A,axis=1),"\n")


A matrix:
[[ 2  4  6]
 [ 8 10 12]] 

Flattened A matrix:
[ 2  4  6  8 10 12] 

mean of A, (flattened): 7.0
mean of A, axis = 0 (column): [5. 7. 9.]
mean of A, axis = 1 (row): [ 4. 10.] 



In [2]:
# np.random.randn, return a sample (or samples) from the “standard normal” distribution.
# It draw samples from a standard Normal distribution (mean=0, stdev=1).
A = np.random.randn(2,4)
print("Random A:\n", A)
print("Row mean of A:",np.mean(A, axis=1))
print("Standard deviation of A:",np.std(A))


Random A:
 [[-0.27450132  0.36467502  1.31009146  0.07812918]
 [-0.73564061 -0.47194381  1.25387019  0.51634588]]
Row mean of A: [0.36959858 0.14065791]
Standard deviation of A: 0.708233791244668


In [3]:
# Construct an array by repeating given number by repetitions

a = np.tile(1, 5)
print(a)

[1 1 1 1 1]


In [4]:
b = np.tile([1, 2], 5)
print(b)

[1 2 1 2 1 2 1 2 1 2]


In [5]:
c = np.tile([1, 2], (5,1))
print(c)

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [1 2]]


In [6]:
c = np.tile([1, 2], (5,1)).T
print(c)

[[1 1 1 1 1]
 [2 2 2 2 2]]


In [7]:
d = np.tile([1, 2], (1,5))
print(d)

[[1 2 1 2 1 2 1 2 1 2]]
