<a href="https://colab.research.google.com/github/kursatkara/MAE_5020_Spring_2025/blob/master/06_01_simple_nn_hand_calculation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Simple feed forward neural network -

import torch

# Input values
i1, i2 = 0.85, 0.25
x = torch.tensor([[i1, i2]], dtype=torch.float32)

# Target output
y_true = torch.tensor([[1.0, 0.0]], dtype=torch.float32)

# Learning rate
lr = 0.3

# Initialize weights and biases
W1 = torch.tensor([[0.1, 0.2, 0.3],
                   [0.4, 0.5, 0.6]], dtype=torch.float32, requires_grad=True)
b1 = torch.tensor([[0.0, 0.0, 0.0]], dtype=torch.float32, requires_grad=True)

W2 = torch.tensor([[0.25, 0.50],
                   [0.1, 0.2],
                   [0.3, 0.4]], dtype=torch.float32, requires_grad=True)
b2 = torch.tensor([[0.0, 0.0]], dtype=torch.float32, requires_grad=True)

# Save old weights
W1_old = W1.clone().detach()
b1_old = b1.clone().detach()
W2_old = W2.clone().detach()
b2_old = b2.clone().detach()

# Forward pass
z1 = x @ W1 + b1
a1 = torch.sigmoid(z1)
print("Hidden layer input (z1):", z1.detach().numpy())
print("Hidden layer output (a1):", a1.detach().numpy())

z2 = a1 @ W2 + b2
y_pred = torch.sigmoid(z2)
print("Output layer input (z2):", z2.detach().numpy())
print("****** Predicted output (y_pred):", y_pred.detach().numpy())

# Compute loss (mean squared error)
loss = torch.mean((y_true - y_pred) ** 2)
print("Loss:", loss.item())

# Backpropagation
loss.backward()

# Update weights
with torch.no_grad():
    W1 -= lr * W1.grad
    b1 -= lr * b1.grad
    W2 -= lr * W2.grad
    b2 -= lr * b2.grad

    # Clear gradients
    W1.grad.zero_()
    b1.grad.zero_()
    W2.grad.zero_()
    b2.grad.zero_()

# Print old vs new weights
print("\nW1 (old):\n", W1_old)
print("W1 (new):\n", W1)
print("\nb1 (old):\n", b1_old)
print("b1 (new):\n", b1)
print("\nW2 (old):\n", W2_old)
print("W2 (new):\n", W2)
print("\nb2 (old):\n", b2_old)
print("b2 (new):\n", b2)

Hidden layer input (z1): [[0.185      0.29500002 0.40500003]]
Hidden layer output (a1): [[0.54611856 0.5732198  0.5998884 ]]
Output layer input (z2): [[0.37381813 0.6276586 ]]
****** Predicted output (y_pred): [[0.59238124 0.65195835]]
Loss: 0.29560136795043945

W1 (old):
 tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000]])
W1 (new):
 tensor([[0.0969, 0.1988, 0.2982],
        [0.3991, 0.4996, 0.5995]], requires_grad=True)

b1 (old):
 tensor([[0., 0., 0.]])
b1 (new):
 tensor([[-0.0037, -0.0014, -0.0021]], requires_grad=True)

W2 (old):
 tensor([[0.2500, 0.5000],
        [0.1000, 0.2000],
        [0.3000, 0.4000]])
W2 (new):
 tensor([[0.2661, 0.4758],
        [0.1169, 0.1746],
        [0.3177, 0.3734]], requires_grad=True)

b2 (old):
 tensor([[0., 0.]])
b2 (new):
 tensor([[ 0.0295, -0.0444]], requires_grad=True)
